### ISSUE TITLE
Windows profiles from Linux host

### ISSUE THREAD

**Issue by patatetom** [moonD4rk/HackBrowserData#145]
hi,

instead of a simple warning (that password decryption cannot take place), `HDB` ends in a panic when `org.freedesktop.secrets` cannot be served : would it be possible to display a warning instead of the panic ?

`HBD` version `0.4.3` is used.

```
/tmp # ./hack-browser-data-linux-amd64 --verbose --browser chrome --profile-path /mnt/sdb1/Users/Test/
[NOTICE] [browser.go:72,pickChromium] find browser chrome_default success  
[NOTICE] [browser.go:72,pickChromium] find browser chrome_network success  
[ERROR] [main.go:60,func1] The name org.freedesktop.secrets was not provided by any .service files  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e0dbb]
goroutine 1 [running]:
hack-browser-data/internal/browingdata.(*Data).Output(0xc000131570?, {0x8f3887, 0x7}, {0xc0001921a0, 0xe}, {0x8ee4fe?, 0x0?})
	/source/internal/browingdata/browsingdata.go:51 +0x7b
main.Execute.func1(0xc0000d60c0?)
	/source/cmd/hack-browser-data/main.go:62 +0x23e
github.com/urfave/cli/v2.(*App).RunContext(0xc0000931e0, {0x975c58?, 0xc000024120}, {0xc0000200a0, 0x5, 0x5})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:322 +0x953
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
main.Execute()
	/source/cmd/hack-browser-data/main.go:73 +0xb90
main.main()
	/source/cmd/hack-browser-data/main.go:24 +0x17
```

once `gnome-keyring` is loaded, `HDB` ends again in another panic :

```
/tmp # ./hack-browser-data-linux-amd64 --verbose --browser chrome --profile-path /mnt/sdb1/Users/Test/
[NOTICE] [browser.go:72,pickChromium] find browser chrome_default success  
[NOTICE] [browser.go:72,pickChromium] find browser chrome_network success  
[INFO] [chromium_linux.go:69,GetMasterKey] chrome_default initialized master key success
panic: crypto/cipher: input not full blocks
goroutine 1 [running]:
crypto/cipher.(*cbcDecrypter).CryptBlocks(0x975200?, {0xc00002c900?, 0xc0001ee400?, 0x10?}, {0xc00002c8d3?, 0xc00010f7e8?, 0x415fe7?})
	/usr/local/go/src/crypto/cipher/cbc.go:119 +0x478
hack-browser-data/internal/decrypter.aes128CBCDecrypt({0xc000027fe0?, 0xc0001e15d8?, 0x0?}, {0xc0001ee400, 0x10, 0x10}, {0xc00002c8d3, 0x24, 0x24})
	/source/internal/decrypter/decrypter.go:186 +0xe2
hack-browser-data/internal/decrypter.Chromium({0xc000027fe0, 0x10, 0x14}, {0xc00002c8d0, 0x27, 0x27})
	/source/internal/decrypter/decrypter_linux.go:9 +0xc5
hack-browser-data/internal/browingdata/password.(*ChromiumPassword).Parse(0xc000174d08, {0xc000027fe0, 0x10, 0x14})
	/source/internal/browingdata/password/password.go:68 +0x3f7
hack-browser-data/internal/browingdata.(*Data).Recovery(0xc000129650?, {0xc000027fe0, 0x10, 0x14})
	/source/internal/browingdata/browsingdata.go:41 +0xdf
hack-browser-data/internal/browser/chromium.(*chromium).BrowsingData(0xc000129650)
	/source/internal/browser/chromium/chromium.go:64 +0xe5
main.Execute.func1(0xc0000ce0c0?)
	/source/cmd/hack-browser-data/main.go:58 +0x1af
github.com/urfave/cli/v2.(*App).RunContext(0xc000096ea0, {0x975c58?, 0xc000024110}, {0xc0000200a0, 0x5, 0x5})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:322 +0x953
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
main.Execute()
	/source/cmd/hack-browser-data/main.go:73 +0xb90
main.main()
	/source/cmd/hack-browser-data/main.go:24 +0x17
```

regards.

_(nb: no problem with Firefox Windows profile under Linux host)_

**Comment by moonD4rk** [comment]
Hi, Thank you for the detailed information. It's impossible to copy a Profile folder from one Host to another and then decrypt it using this tool. The prerequisite for decrypting the data is to obtain the MasterKey, which is generated at the time of browser installation and is unique for each Host. On Windows, the [DPAPI](https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-use-data-protection) is used to generate the key, and on Linux it is the [D-Bus](https://en.wikipedia.org/wiki/D-Bus). 
If you copy the encrypted file to another machine, the original masterkey is not available, so the decryption will not be successful.

**Comment by Kirkezz** [comment]
I had the same problem with "panic: crypto/cipher: input not full blocks". Found the following workaround:
`sudo wine hack-browser-data-windows-64bit.exe -b chrome -p '/mnt/windows/Users/User/AppData/Local/Google/Chrome/User Data/Default/'`

It didn't restored passwords because of

"[ERROR] [password.go:71,Parse] Invalid data.
0140:err:crypt:valid_protect_data info0 magic value not matched !
0140:err:crypt:valid_protect_data unrecognized CryptProtectData block
0140:fixme:crypt:CryptUnprotectData CryptUnprotectData received a DATA_BLOB that seems to have NOT been generated by Wine.  Please enable tracing ('export WINEDEBUG=crypt') to see details."

but everything else was restored.
