### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rtfghd** [moonD4rk/HackBrowserData#157]
```
[[1mNOTICE[0m] [browser.go:46,pickChromium] [1mfind browser Yandex failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [browser.go:46,pickChromium] [1mfind browser 360speed failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [browser.go:50,pickChromium] [1mfind browser QQ success[0m  
[[1mNOTICE[0m] [browser.go:52,pickChromium] [1mfind browser qq_default success[0m  
[[1mNOTICE[0m] [browser.go:46,pickChromium] [1mfind browser Chrome failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [browser.go:46,pickChromium] [1mfind browser Chromium failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [browser.go:46,pickChromium] [1mfind browser Chrome Beta failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [browser.go:46,pickChromium] [1mfind browser Opera failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [browser.go:46,pickChromium] [1mfind browser OperaGX failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [browser.go:46,pickChromium] [1mfind browser Vivaldi failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [browser.go:46,pickChromium] [1mfind browser CocCoc failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [browser.go:46,pickChromium] [1mfind browser Brave failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [browser.go:50,pickChromium] [1mfind browser Microsoft Edge success[0m  
[[1mNOTICE[0m] [browser.go:52,pickChromium] [1mfind browser microsoft_edge_default success[0m  
[[1mNOTICE[0m] [browser.go:52,pickChromium] [1mfind browser microsoft_edge_network success[0m  
[[1mNOTICE[0m] [browser.go:90,pickFirefox] [1mfind browser firefox Firefox failed, profile folder does not exist[0m  
[[35mERROR[0m] [main.go:60,func1] [35mopen bookmark: Access is denied.[0m  
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xaa979b]

goroutine 1 [running]:
hack-browser-data/internal/browingdata.(*Data).Output(0xc00017c0e0?, {0xc94bde, 0x7}, {0xc0001d22f0, 0xa}, {0xc8f962?, 0x0?})
	/source/internal/browingdata/browsingdata.go:51 +0x7b
main.Execute.func1(0xc000158240?)
	/source/cmd/hack-browser-data/main.go:62 +0x23e
github.com/urfave/cli/v2.(*App).RunContext(0xc000154680, {0xd152c8?, 0xc0000180d8}, {0xc000030080, 0x3, 0x4})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:322 +0x953
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
main.Execute()
	/source/cmd/hack-browser-data/main.go:73 +0xb90
main.main()
	/source/cmd/hack-browser-data/main.go:24 +0x17


```

**Comment by moonD4rk** [comment]
Provide more detailed information about bugs, OS versions and browser versions.

**Comment by rtfghd** [comment]
> Provide more detailed information about bugs, OS versions and browser versions.

windows11 家庭中文版 10.0.22000
报错那一行看不出来是什么原因报错了

**Comment by mmsrubar** [comment]
Hello, I will use this issue and open a new ticket because I'm facing a similar issue.

I'm using version 0.5.5 of HackBrowserData compiled from source. The machine is a Windows 10 box.

```ps1
PS C:\Users\admin> Get-WmiObject Win32_OperatingSystem
SystemDirectory : C:\Windows\system32    
Organization    : 
BuildNumber     : 19045
RegisteredUser  : Windows User
SerialNumber    : 00328-00000-00000-AA767
Version         : 10.0.19045

PS C:\Users\admin> ..\user\AppData\Roaming\hack-browser-data.exe -v
hack-browser-data version 0.5.0
```
I'm logged in as user admin (local Administrator) and trying to execute HackBrowserData using `runas` under user with name **user**. The executable is located in the `C:\Users\user\AppData\Roaming\` directore which is writable for the user account.

```ps1
PS C:\Users\admin> whoami /user /groups

USER INFORMATION
----------------

User Name             SID
===================== ==============================================
desktop-9sq5vt2\admin S-1-5-21-3016369623-1103743024-2793333192-1000


GROUP INFORMATION
-----------------

Group Name                                                    Type             SID          Attributes
============================================================= ================ ============ ===============================================================
Everyone                                                      Well-known group S-1-1-0      Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\Local account and member of Administrators group Well-known group S-1-5-114    Mandatory group, Enabled by default, Enabled group
BUILTIN\Administrators                                        Alias            S-1-5-32-544 Mandatory group, Enabled by default, Enabled group, Group owner
BUILTIN\Users                                                 Alias            S-1-5-32-545 Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\NETWORK                                          Well-known group S-1-5-2      Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\Authenticated Users                              Well-known group S-1-5-11     Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\This Organization                                Well-known group S-1-5-15     Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\Local account                                    Well-known group S-1-5-113    Mandatory group, Enabled by default, Enabled group
NT AUTHORITY\NTLM Authentication                              Well-known group S-1-5-64-10  Mandatory group, Enabled by default, Enabled group
Mandatory Label\High Mandatory Level                          Label            S-1-16-12288
```
When I try to execute the binary using runas it seems to have a problem to create the directory where results should be written.

![Screenshot from 2023-08-24 12-53-57](https://github.com/moonD4rk/HackBrowserData/assets/4816654/5c7542c7-3f40-4476-9404-366fe5ae73f8)

When I try something more simple like create a folder using mkdir in the same directory it works just fine and the folder is created successfully. 

![Screenshot from 2023-08-24 12-55-36](https://github.com/moonD4rk/HackBrowserData/assets/4816654/c44380ec-4fe3-4958-acdb-fc5147368dd3)

What is strange to me is that ERROR message is changing every time I try to execute the binary. 

```
[ERROR] [main.go::55,func1] mkdir sessionStorage: Access is denied.
[ERROR] [main.go::55,func1] mkdir localStorage: Access is denied.
[ERROR] [main.go::55,func1] open cookie: Access is denied.
[ERROR] [main.go::55,func1] open history: Access is denied.
[ERROR] [main.go::55,func1] open download: Access is denied.
[ERROR] [main.go::55,func1] open chromiumKey: Access is denied.
```

Hopes the provided info will help.

**Comment by moonD4rk** [comment]
Both problems are gone:

- locked-file access — #516 added `filemanager`, which reads the file through the browser's own handle on Windows
- the nil-pointer panic — the old `internal/browingdata` package was removed in the v2 rewrite (#540); output errors are returned now

Please reopen if it still reproduces on a recent release.
