### ISSUE TITLE
On Linux Chrome with kdewallet5 enabled, hack fails

### ISSUE THREAD

**Issue by zyf0330** [moonD4rk/HackBrowserData#161]
**Describe the bug**
Use `./hack-browser-data -vv` paste result here

```
[NOTICE] [browser.go:72,pickChromium] find browser chrome_def success
[NOTICE] [browser.go:72,pickChromium] find browser chrome_guest_user success
[NOTICE] [browser.go:72,pickChromium] find browser chrome_default success
[ERROR] [main.go:60,func1] The name org.freedesktop.secrets was not provided by any .service files
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e0dbb]

goroutine 1 [running]:
hack-browser-data/internal/browingdata.(*Data).Output(0xc0000c0000?, {0x7ffc390f0725, 0x7}, {0xc00041aa90, 0xa}, {0x7ffc390f071a?, 0x0?})
        /source/internal/browingdata/browsingdata.go:51 +0x7b
main.Execute.func1(0xc0000ee0c0?)
        /source/cmd/hack-browser-data/main.go:62 +0x23e
github.com/urfave/cli/v2.(*App).RunContext(0xc0000ad1e0, {0x975c58?, 0xc00002a148}, {0xc000020080, 0x8, 0x8})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:322 +0x953
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
main.Execute()
        /source/cmd/hack-browser-data/main.go:73 +0xb90
main.main()
        /source/cmd/hack-browser-data/main.go:24 +0x17
```

**Desktop (please complete the following information):**
 - OS Name: Ubuntu 
 - Browser Name: Google Chrome
 - Browser Version: 104.0.5112.79 (Official Build) (64-bit)

**Additional context**

**Comment by DeadNumbers** [comment]
Is `libsecret` installed?

**Comment by zyf0330** [comment]
```
libsecret-1-0/jammy,now 0.20.5-2 amd64 [installed]
libsecret-1-dev/jammy,now 0.20.5-2 amd64 [installed]
libsecret-common/jammy,jammy,now 0.20.5-2 all [installed]
libsecret-tools/jammy,now 0.20.5-2 amd64 [installed]
```

**Comment by DeadNumbers** [comment]
@zyf0330 also is `gnome-keyring` allready installed?

**Comment by zyf0330** [comment]
It is not installed.
```
python3-keyring/jammy,jammy,now 23.5.0-1 all [installed]
python3-keyrings.alt/jammy,jammy,now 4.1.0-1 all [installed]
ubuntu-keyring/jammy,jammy,now 2021.03.26 all [installed]
```

**Comment by moonD4rk** [comment]
Cross-reference: #572 tracks the broader design work for native KWallet5/6 support. Your crash will resolve once that lands.

**Comment by DUptain1993** [comment]
Addressed (as far as in-scope) in https://github.com/moonD4rk/HackBrowserData/pull/643 — see the PR description for what was fixed vs documented limits.
