### ISSUE TITLE
Key not valid for use in specified state?

### ISSUE THREAD

**Issue by badboycxcc** [moonD4rk/HackBrowserData#217]
```
hack-browser-data-windows-64bit.exe -b chrome -p "C:\Users\xxx\Desktop\xxx\xxx\a\User Data"
[NOTICE] [browser.go:73,pickChromium] find browser chrome_106_0_5249_119 success
[NOTICE] [browser.go:73,pickChromium] find browser chrome_107_0_5304_107 success
[NOTICE] [browser.go:73,pickChromium] find browser chrome_108_0_5359_125 success
[NOTICE] [browser.go:73,pickChromium] find browser chrome_default success
[ERROR] [main.go:60,func1] Key not valid for use in specified state.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6f837b]

goroutine 1 [running]:
hack-browser-data/internal/browingdata.(*Data).Output(0xc0004953b0?, {0x8e74b9, 0x7}, {0xc000021260, 0x15}, {0x8e2217?, 0x0?})
        /source/internal/browingdata/browsingdata.go:51 +0x7b
main.Execute.func1(0xc00011e240?)
        /source/cmd/hack-browser-data/main.go:62 +0x23e
github.com/urfave/cli/v2.(*App).RunContext(0xc000084ea0, {0x96bf48?, 0xc00009e0b0}, {0xc0000ce000, 0x5, 0x8})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:322 +0x97c
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
main.Execute()
        /source/cmd/hack-browser-data/main.go:73 +0x7f6
main.main()
        /source/cmd/hack-browser-data/main.go:24 +0x17
```

**Comment by moonD4rk** [comment]
Duplicate with https://github.com/moonD4rk/HackBrowserData/issues/41 https://github.com/moonD4rk/HackBrowserData/issues/214
Detail in this Replay https://github.com/moonD4rk/HackBrowserData/issues/188#issuecomment-1465168108
