### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kuA35sSaasd** [moonD4rk/HackBrowserData#230]
**Describe the bug**
Use `./hack-browser-data -vv` paste result here
```
test.exe -vv
[NOTICE] [browser.go:47,pickChromium] find browser CocCoc failed, profile folder does not exist  
[NOTICE] [browser.go:56,pickChromium] find browser qq_default success  
[NOTICE] [browser.go:47,pickChromium] find browser DC failed, profile folder does not exist  
[NOTICE] [browser.go:47,pickChromium] find browser Yandex failed, profile folder does not exist  
[NOTICE] [browser.go:56,pickChromium] find browser 360speed_default success  
[NOTICE] [browser.go:56,pickChromium] find browser sogou_default success  
[NOTICE] [browser.go:47,pickChromium] find browser Microsoft Edge failed, profile folder does not exist  
[NOTICE] [browser.go:47,pickChromium] find browser Opera failed, profile folder does not exist  
[NOTICE] [browser.go:47,pickChromium] find browser OperaGX failed, profile folder does not exist  
[NOTICE] [browser.go:47,pickChromium] find browser Vivaldi failed, profile folder does not exist  
[NOTICE] [browser.go:47,pickChromium] find browser Brave failed, profile folder does not exist  
[NOTICE] [browser.go:56,pickChromium] find browser chrome_default success  
[NOTICE] [browser.go:56,pickChromium] find browser chrome_def success  
[NOTICE] [browser.go:47,pickChromium] find browser Chromium failed, profile folder does not exist  
[NOTICE] [browser.go:47,pickChromium] find browser Chrome Beta failed, profile folder does not exist  
[NOTICE] [browser.go:91,pickFirefox] find browser firefox Firefox failed, profile folder does not exist  
[ERROR] [main.go:55,func1] open : The system cannot find the file specified.  
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff6d5f2be9b]

goroutine 1 [running]:
github.com/moond4rk/HackBrowserData/browingdata.(*Data).Output(0xc0000a6d00?, {0x7ff6d60d6971, 0x7}, {0xc000197210, 0xa}, {0x7ff6d60d161d?, 0xf6d5ddd2c5?})
	github.com/moond4rk/HackBrowserData/browingdata/browsingdata.go:52 +0x7b
main.Execute.func1(0xc000186160?)
	./main.go:57 +0x24a
github.com/urfave/cli/v2.(*Command).Run(0xc000186160, 0xc0000d2540, {0xc0000963a0, 0x2, 0x2})
	github.com/urfave/cli/v2@v2.25.0/command.go:273 +0xa42
github.com/urfave/cli/v2.(*App).RunContext(0xc000182000, {0x7ff6d6154808?, 0xc00009e078}, {0xc0000963a0, 0x2, 0x2})
	github.com/urfave/cli/v2@v2.25.0/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.25.0/app.go:309
main.Execute()
	./main.go:69 +0x8b7
main.main()
	./main.go:24 +0x17
```

**Desktop (please complete the following information):**
 - OS Name: Windows 10 专业版 64 Bit
 - Browser Name:Chrome
 - Browser Version: Chrome 114.0.5735.199

**Additional context**

**Comment by moonD4rk** [comment]
Are you using a self-compiled version or did you download the release? Can you check the version by running `./hack-browser-data -v`?

**Comment by a-urth** [comment]
@kuA35sSaasd can you try it from latest main branch? I'm pretty sure i've fixed this issue recently.
