### ISSUE TITLE
编译后无法正确运行

### ISSUE THREAD

**Issue by L-codes** [moonD4rk/HackBrowserData#27]
Mac上跨平台编译Windows exe
编译后无法正确运行
```
browser.go:121: error Chrome find bookmark file failed, ERR:find Bookmarks failed
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x113e396]

goroutine 1 [running]:
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.14.5/libexec/src/database/sql/sql.go:3063 +0x76
database/sql.(*Rows).Close(...)
        /usr/local/Cellar/go/1.14.5/libexec/src/database/sql/sql.go:3059
hack-browser-data/core/common.(*historyData).ChromeParse.func2(0x0)
        /intranet_tools/mutil/HackBrowserData/core/common/parse.go:312 +0x37
panic(0x1274840, 0x14c62b0)
        /usr/local/Cellar/go/1.14.5/libexec/src/runtime/panic.go:969 +0x166
database/sql.(*Rows).Next(0x0, 0x13188c0)
        /usr/local/Cellar/go/1.14.5/libexec/src/database/sql/sql.go:2744 +0x30
hack-browser-data/core/common.(*historyData).ChromeParse(0xc000078ba0, 0xc000016760, 0x10, 0x14, 0x0, 0x0)
        /intranet_tools/mutil/HackBrowserData/core/common/parse.go:316 +0x137
hack-browser-data/cmd.Execute.func1(0xc00010e740, 0xc00000ca00, 0xc)
        /intranet_tools/mutil/HackBrowserData/cmd/cmd.go:71 +0x537
github.com/urfave/cli/v2.(*App).RunContext(0xc000001200, 0x13188c0, 0xc0000181e0, 0xc000010210, 0x1, 0x1, 0x0, 0x0)
        /Users/l/gocode/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x70b
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/l/gocode/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
hack-browser-data/cmd.Execute()
        /intranet_tools/mutil/HackBrowserData/cmd/cmd.go:100 +0x739
main.main()
        /intranet_tools/mutil/HackBrowserData/main.go:8 +0x20
```

**Comment by moonD4rk** [comment]
用到的 `Sqlite` 库需要 CGO，跨平台编译时需要提前安装目标平台的 GCC 库。
```
brew install mingw-w64

CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC="x86_64-w64-mingw32-gcc" go build
```

**Comment by L-codes** [comment]
Mac 编译 Linux ELF 文件也会遇到同样的问题，请问应该怎么解决？

**Comment by moonD4rk** [comment]
没遇到过具体场景，不太清楚。可以看看其他辅助交叉编译的工具 `https://github.com/karalabe/xgo`，或者使用 `github workflow` 或是虚拟机。

**Comment by L-codes** [comment]
@moonD4rk 我试了musl-cross 能编译成功，但是执行的时候会说找不到该文件，确定文件存在
Mac用mingw-w64解决了 windows exe的问题，但是linux的我在Mac上存在另一个问题
```
brew install FiloSottile/musl-cross/musl-cross
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CC=x86_64-linux-musl-gcc go build main.go
```

**Comment by moonD4rk** [comment]
```
brew install FiloSottile/musl-cross/musl-cross

CC=x86_64-linux-musl-gcc CXX=x86_64-linux-musl-g++ GOARCH=amd64 GOOS=linux CGO_ENABLED=1 go build -ldflags "-linkmode external -extldflags -static"
```
